name: "Publish: Crustina"

on:
    push:
        paths:
            - crustina/src/**
            - .github/workflows/crustina-publish.yml

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - uses: actions/cache@v2
              id: cache
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Install Dependencies
              if: ${{ steps.cache.outputs.cache-hit != 'true' }}
              run: yarn
              
            - name: Build Axeroni
              run: cd axeroni && yarn build
              
            - name: Build
              run: cd crustina && yarn build
              
              

            - name: Update Version
              run: cd ./crustina && yarn version:update

            - name: Publish to NPM
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  package: ./crustina/package.json

            - run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git pull
                  git add .
                  git commit -m 'chore(crustina): update version'
                  git push
