name: "Lint and Test: Hothouse"

on:
    push:
        paths:
            - hothouse/**
    pull_request:
        paths:
            - hothouse/**

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - run: |
                  yarn
                  cd ./hothouse
                  yarn lint
                  yarn build
                  yarn test
