name: "Lint and Test: Nightshade"

on:
    push:
        paths:
            - nightshade/**

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - run: yarn
            - run: cd ./nightshade
            - run: yarn lint
            - run: yarn build
            - run: yarn test
