name: "Lint and Test: Nightshade"

on:
    push:
        paths:
            - nightshade/**

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - uses: actions/cache@v2
              id: cache
              with:
                 path: "**/node_modules"
                 key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                 restore-keys: |
                    ${{ runner.os }}-yarn-

            - name: Install Dependencies
              if: ${{ steps.cache.outputs.cache-hit != 'true' }}
              run: cd ./nightshade yarn
            - run: cd ./nightshade && yarn lint
            - run: cd ./nightshade && yarn build
            - run: cd ./nightshade && yarn test
