name: Update Lock File

on:
    push:
        branches: master
        paths:
            - '**package.json'
            - .github/workflows/update-lock-file.yml
    pull_request_target:
        paths:
            - '**package.json'
            - .github/workflows/update-lock-file.yml

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x
                  
            - name: Install Deps
              run: yarn
              
            - name: Commit Lock File
              uses: EndBug/add-and-commit@v7
              with:
                author_name: CreeperPlanet26
                author_email: fortniteplanet26@gmail.com
                message: 'chore(deps): update lock file'
