name: "Lint and Test: Zzaria"

on:
    push:
        branches: master
        paths:
            - zzaria/**
            - yarn.lock
            - .eslintrc.json
            - .prettierrc.js
            - .github/workflows/zzaria-lint-test.yml
    pull_request_target:
        paths:
            - zzaria/**
            - eslintrc.json
            - prettierrc.js
            - .github/workflows/zzaria-lint-test.yml

jobs:

    lint: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x
                  
            - uses: actions/cache@v2
              id: cache
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install Dependencies
              if: ${{ steps.cache.outputs.cache-hit != 'true' }}
              run: cd ./zzaria && yarn
            - name: Lint  
              run: cd ./zzaria && yarn lint

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - uses: supercharge/mongodb-github-action@1.4.0
              with:
                  mongodb-version: 4.0

            - uses: actions/cache@v2
              id: cache
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install Dependencies
              if: ${{ steps.cache.outputs.cache-hit != 'true' }}
              run: cd ./zzaria && yarn

            - name: Build Axeroni
              run: cd ./axeroni && yarn build  
              
            - name: Build
              run: cd ./zzaria && yarn build
              
            - name: Test
              run: cd ./zzaria && yarn test:e2e
              env:
                  MONGO_URI: mongodb://localhost/test
                  JWT_SECERT: test
                  BOT_TOKEN: ${{secrets.ZZARIA_BOT_TOKEN}}
