name: "Deploy: Zzaria"

on:
    push:
        branches:
            - master
        paths:
            - zzaria/**
            - yarn.lock
            - .github/workflows/zzaria-deploy.yml

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - uses: actions/cache@v2
              id: cache
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Install Dependencies
              if: ${{ steps.cache.outputs.cache-hit != 'true' }}
              run: yarn

            - name: Check if Axeroni is up to date
              run: cd ./axeroni && yarn version:check

            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.ZZARIA_API_KEY}}
                  heroku_app_name: "tts-api-prod"
                  heroku_email: ${{secrets.ZZARIA_EMAIL}}
                  appdir: "zzaria"
