name: "Lint and Test: Zzaria"

on: 

     push:
         branches: master
         paths:
              - zzaria/**
     pull_request_target: 
         paths: 
               - zzaria/**
 

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - uses: supercharge/mongodb-github-action@1.4.0
              with:
                  mongodb-version: 4.0

            - run: cd ./zzaria && yarn
            - run: cd ./zzaria && yarn lint
            - run: cd ./zzaria && yarn build
            - run: cd ./zzaria && yarn test:e2e
              env:
                  MONGO_URI: mongodb://localhost/test
                  BOT_TOKEN: ${{secrets.ZZARIA_BOT_TOKEN}}
