name: "Lint and Test: Zzaria"

on:
    push:
        paths:
            - zzaria/**

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - run: cd ./zzaria && yarn
            - run: cd ./zzaria && yarn lint
            - run: cd ./zzaria && yarn run build
            - run: cd ./zzaria && yarn test
